data:
  test:
    platform: tb
    host: wangcai-${env}.1yangai.com
    test_tools_new: http://test-tools-${env}.1yangai.com
    api_host: https://api-${env}.1yangai.com

    p_path: pulsar://pulsar-cluster01-slb:6650
    topic: persistent://reminder/trade/order_tb
    orderRateQueue: persistent://marketing/taobao/orderrate
    logisticsQueue: persistent://reminder/tmc/logistics_tb
    refundQueue: persistent://reminder/tmc/refund_tb

    sign: ca61da42f143ef040fc22afee498a622

    shopName: ${shopName}
    refund_id: 58379106742933796

    seller_name: ${shopName}