logging:
  level:
    root: FATAL
client:
  protocol: http
  timeOut: 5
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36"
    Accept-Encoding: "gzip, deflate"
    Connection: "keep-alive"
    Content-Language: "zh-CN"
    Content-Type: "application/json;charset=UTF-8"
    Accept: "application/json, text/plain, */*"