data:
  test:
    host: pdd-test-sc.xiaoduoai.com
    mock_host: http://pdd-test-sc.xiaoduoai.com/tester/mock/
    shopName: 会话中台组:pdd66974974631
    mall_id: 783353010
    seller_name: pdd66974974631
    shop: 会话中台组
    sign: ca61da42f143ef040fc22afee498a622
    buyer: 5083583826
    platform: pdd
    child_seller: 会话中台组:pdd66974974631
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"