data:
  test:
    host: co-test1.xiaoduoai.com
    platform: taodongli
    co_test: https://co-test1.xiaoduoai.com
    co_test_username: 淘动力
    co_test_password: 123456

client:
  protocol: https
  headers:
    Xiaoduo-Platform: taodongli