data:
  test:
    host: jd-qa.xiaoduoai.com
    mock_host: http://mock-server-jd.xiaoduoai.com
    shopName: 测试ckm
    seller_name: 友发轮胎专营店:测试ckm
    shop: 测试ckm
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester001
    platform: jd
    child_seller: 友发轮胎专营店:测试ckm
    test_tools: http://zhy-jd.xiaoduoai.com
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"