data:
  test:
    platform: tb
    host: wangcai-${env}.xiaoduoai.com
    test_tools: http://zhy-${env}.xiaoduoai.com
    api_host: https://api-${env}.xiaoduoai.com
    mc_test: https://mc-${env}.xiaoduoai.com
    seller_host: https://seller.xiaoduoai.com

    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-${env}
    orderRateQueue: persistent://marketing/taobao/orderrate-${env}
    logisticsQueue: persistent://reminder/tmc/logistics_tb_test
    refundQueue: persistent://reminder/tmc/refund_tb_test

    sign: ca61da42f143ef040fc22afee498a622

    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    buyer: tester002
    child_seller: wangjq_1990:xiaoduo1
    child_seller_name: xiaoduo1
    child_seller2: wangjq_1990:lzp
    child_seller3: wangjq_1990:老弗丁
    refund_id: 44636195945933796