data:
  test:
    host: jd-qa.xiaoduoai.com
    mock_host: http://mock-server-jd.xiaoduoai.com
    shopName: 测试ckm
    seller_name: 友发轮胎专营店:测试ckm
    shop: JQ铅笔
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5d522cb46f7d26000f36d97e
    buyer: wangjq729_12
    platform: jd
    child_seller: 友发轮胎专营店:测试ckm
    jenkins_url: http://10.0.0.152:8080/job/java-interface-test-jdsop/allure/