data:
  test:
    host: ${env}.xiaoduoai.com
    shopName: 智晓多谋生鲜专营店
    seller_name: 晓多生鲜-zdx
    shop: 智晓多谋生鲜专营店
    platform: jd
    child_seller: 晓多生鲜-ld
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"