data:
  test:
    host: wangcai-test2.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5d832c02237402000b960a71
    buyer: wangjq_xd
    platform: taodongli
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-taodongli-test2
    test_tools: http://zhy-test2.xiaoduoai.com
    co_test: https://co-test2.xiaoduoai.com
    co_test_username: 淘动力
    co_test_password: 8Axu93eWyt
    child_seller: wangjq_1990:xiaoduo1
client:
  headers:
    Xiaoduo-Platform: taodongli