data:
  test:
    host: jd-test-cm.xiaoduoai.com
    shopName: shuangqing2015
    seller_name: 双庆家居京东自营旗舰店:shuangqing2015
    shop: 测试ckm
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester002
    platform: jd
    child_seller: 双庆家居京东自营旗舰店:shuangqing2019
    test_tools: http://test-tools.xiaoduoai.com
    topic: persistent://zhongtai/reminder/rmd-trade-jd
client:
  protocol: http
  timeOut: 30
  headers:
    Xiaoduo-Platform: jdzy
    Content-Type: "application/json;charset=UTF-8"