data:
  test:
    host: ${env}.xiaoduoai.com
    shopName: 晓多生鲜-fkl
    seller_name: 智晓多谋生鲜专营店:晓多生鲜-fkl
    shop: 智晓多谋生鲜专营店
    buyer: tester002
    platform: jd
    child_seller: 智晓多谋生鲜专营店:晓多生鲜-hxx
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"