data:
  test:
    platform: taodongli
    sign: ca61da42f143ef040fc22afee498a622
    host: wangcai-${env}.xiaoduoai.com
    test_tools: http://zhy-${env}.xiaoduoai.com
    co_test: https://co-${env}.xiaoduoai.com
    mc_test: https://mc-${env}.xiaoduoai.com

    p_path: pulsar://pulsar-cluster01-slb:6650
    topic: persistent://reminder/trade/order_taodongli
    orderRateQueue: persistent://marketing/taobao/orderrate
    logisticsQueue: persistent://reminder/tmc/logistics_tb
    refundQueue: persistent://reminder/tmc/refund_taodongli

    co_test_username: 淘动力
    co_test_password: 123456

    shopName: ${shopName}
    refund_id: 58379106742933796

client:
  headers:
    Xiaoduo-Platform: taodongli