data:
  test:
    host: wangcai-test2.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    buyer: wangjq_xd
    platform: taodongli
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-taodongli-test2
    test_tools: http://zhy-test2.xiaoduoai.com
    co_test: https://co-test2.xiaoduoai.com
    co_test_username: 淘动力
    co_test_password: 123456
    child_seller: wangjq_1990:xiaoduo1
    refund_id: 44636195945933796
    orderRateQueue: persistent://marketing/taobao/orderrate-taodongli
    logisticsQueue: persistent://reminder/tmc/logistics_tb_test
client:
  headers:
    Xiaoduo-Platform: taodongli