data:
  test:
    host: jd-qa.xiaoduoai.com
    mock_host: http://mock-server-jd.xiaoduoai.com
    shopName: 测试ckm
    seller_name: 友发轮胎专营店:测试ckm
    shop: 测试ckm
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5de26cae9e3aad000efa4475
    buyer: wangjq729_12
    platform: jd
    child_seller: 友发轮胎专营店:测试ckm
    test_tools: http://zhy-jd.xiaoduoai.com