data:
  test:
    host: wangcai-test3.xiaoduoai.com
    shopName: 杜可风按
    seller_name: 杜可风按
    shop: 杜可风按
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5bff714abf1f8f5726a6360f
    buyer: wangjq_xd
    platform: tb
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-test3
    test_tools: http://zhy-test3.xiaoduoai.com
    dataadmin: http://dataadmin-test3.xiaoduoai.com
    dataadmin_username: admin
    dataadmin_password: 123456