data:
  test:
    host: wangcai-test3.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5d81f3c669da40000d6b97bb
    buyer: wangjq_xd
    platform: tb
    jenkins_url: http://10.0.0.152:8080/job/java-interface-test-tb/allure/
    mock_host: http://mock-server.xiaoduoai.com