data:
  test:
    platform: taodongli
    sign: ca61da42f143ef040fc22afee498a622
    host: wangcai-test2.xiaoduoai.com
    test_tools: http://zhy-test2.xiaoduoai.com
    co_test: https://co-test2.xiaoduoai.com
    mc_test: https://mc-test2.xiaoduoai.com

    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-taodongli-test2
    orderRateQueue: persistent://marketing/taobao/orderrate-taodongli
    logisticsQueue: persistent://reminder/tmc/logistics_tb_test
    refundQueue: persistent://reminder/tmc/refund_tb_test

    co_test_username: 淘动力
    co_test_password: 123456

    shopName: ${shopName}
    refund_id: 44636195945933796

client:
  headers:
    Xiaoduo-Platform: taodongli