data:
  test:
    host: jd-qa.xiaoduoai.com
    shopName: 测试ckm
    seller_name: 友发轮胎专营店:测试ckm
    shop: 测试ckm
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester002
    platform: jd
    child_seller: 友发轮胎专营店:测试ckm
    test_tools: http://test-tools.xiaoduoai.com
    test_tools_new: http://test-tools-${env}.xiaoduoai.com
    topic: persistent://zhongtai/reminder/rmd-trade-jd
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"