data:
  test:
    host: wangcai-test1.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester001
    platform: tb
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-test
    test_tools: http://zhy-test1.xiaoduoai.com
    mc_test: https://mc-test1.xiaoduoai.com
    child_seller: wangjq_1990:xiaoduo1
    child_seller_name: xiaoduo1
    seller_host: https://seller.xiaoduoai.com
    refund_id: 44636195945933796
    orderRateQueue: persistent://marketing/taobao/orderrate-test1
    logisticsQueue: persistent://reminder/tmc/logistics_tb_test