data:
  test:
    host: jd-${env}.xiaoduoai.com
    shopName: xinke2015
    seller_name: 新科影音京东自营旗舰店:xinke2015
    shop: 新科影音京东自营旗舰店
    buyer: tester002
    platform: jd
    child_seller: 新科影音京东自营旗舰店:xinke2015
client:
  protocol: http
  timeOut: 30
  headers:
    Xiaoduo-Platform: jdzy
    Content-Type: "application/json;charset=UTF-8"