data:
  test:
    host: wangcai-test2.xiaoduoai.com
    shopName: 杜可风按
    seller_name: 杜可风按
    shop: 杜可风按
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester001
    platform: tb
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-test2
    test_tools: http://zhy-test2.xiaoduoai.com