data:
  test:
    host: wangcai-test2.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester002
    platform: tb
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-test2
    test_tools: http://zhy-test2.xiaoduoai.com
    api_host: https://api-test2.xiaoduoai.com
    mc_test: https://mc-test2.xiaoduoai.com
    child_seller: wangjq_1990:xiaoduo1
    child_seller2: wangjq_1990:lzp
    child_seller3: wangjq_1990:老弗丁
    child_seller_name: xiaoduo1
    seller_host: https://seller.xiaoduoai.com
    refund_id: 44636195945933796
    orderRateQueue: persistent://marketing/taobao/orderrate-test2
    logisticsQueue: persistent://reminder/tmc/logistics_tb_test