data:
  test:
    host: wangcai-test3.xiaoduoai.com
    shopName: wangjq_1990
    seller_name: wangjq_1990
    shop: wangjq_1990
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5d81f3c669da40000d6b97bb
    buyer: wangjq_xd
    platform: tb
    mock_host: http://mock-server.xiaoduoai.com
    p_path: pulsar://pulsar-test-1:6650
    topic: persistent://public/default/rmd-trade-tb-test3
    test_tools: http://zhy-test3.xiaoduoai.com
    dataadmin: http://dataadmin-test3.xiaoduoai.com
    dataadmin_username: admin
    dataadmin_password: 123456
    child_seller: wangjq_1990:xiaoduo1
    child_seller_name: xiaoduo1
    seller_host: https://seller.xiaoduoai.com