data:
  test:
    host: pdd-test.xiaoduoai.com
    pdd_api_host: http://pdd-api-test.xiaoduoai.com
    mock_host: http://mock-server-pdd.xiaoduoai.com
    reminder_pdd_host: http://reminder-pdd-test.xiaoduoai.com
    shopName: 会话中台组:pdd66974974631
    seller_name: pdd66974974631
    shop: 会话中台组
    sign: ca61da42f143ef040fc22afee498a622
    shop_id: 5d4b9518dfc90e000ad6ca95
    platform: pdd