data:
  test:
    host: jd-${env}.xiaoduoai.com
    shopName: 美的软水自营小唐
    seller_name: 美的净水软水京东自营旗舰店:美的软水自营小唐
    shop: 美的净水软水京东自营旗舰店
    sign: ca61da42f143ef040fc22afee498a622
    buyer: tester002
    platform: jd
    child_seller: 美的净水软水京东自营旗舰店:美的软水自营小唐
    test_tools: http://test-tools.xiaoduoai.com
    test_tools_new: http://test-tools-${env}.xiaoduoai.com
    topic: persistent://zhongtai/reminder/rmd-trade-jd
client:
  protocol: http
  timeOut: 30
  headers:
    Xiaoduo-Platform: jd
    Content-Type: "application/json;charset=UTF-8"