data:
  test:
    platform: tanmarket
    host: blue.wechatsi.com
client:
  headers:
    Authorization: |
      eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzkxMTU2OTMsInBheWxvYWQiOiJ7XCJjb3JwaWRcIjpcInd3ZDA3NGYzOTY4ZjU2ZGNiMFwiLFwiaWRcIjo0NDU0OTk5MDAwNzQxNzYsXCJ1c2VySWRcIjpcImFkbWluX2JqanhcIixcImlzQWRtaW5cIjoxLFwiZGVwYXJ0bWVudElkc1wiOm51bGwsXCJtYW5hZ2VEZXB0c1wiOlwiW11cIixcImRldmljZVwiOlwid2ViXCIsXCJuYW1lXCI6XCJhZG1pblwiLFwidmFndWVcIjowLFwiX2xlYWRlclwiOnRydWV9IiwiZXhwIjoxNjc5Mjg4NDkzfQ.kaZZgR95bqGDoyJXGRrbRKoPJDOvMNcHQeOiSTIg1UP-GImL4rsIXGP9SBEqGsG_CerNSDqBsGOrbb5x69XoXlYjoLsNvcmwrLZdU0HmzSEYMARICKzA04RaQ0v22EvxAYZu1Oqq6A32_nj2k3jnCzVMBfRUS449SGBvh7ErIJ3dKByWxPuyAABgXn2Ur3p2cgLY3B046KTKUsPgafdwNyechh5x18I379nhDgnuKrwgM5kejMlTTwMg1KY7OUI8thoaVhQCEq3YMhejOA4eih8syIbKxGy2X5WySHKWpbvvY8hlHlsxyMWHdc7vmvZ2sBE0q_cL3cC2iCbPB1E5Mg
      
