data:
  test:
    platform: taodongli
    host: wangcai-${env}.xiaoduoai.com
    co_test: https://co-${env}.xiaoduoai.com

    co_test_username: 淘动力
    co_test_password: xinghuan123

    shopName: ${shopName}
client:
  headers:
    Xiaoduo-Platform: taodongli