data:
  test:
    platform: bitunix
    host: api.test.searchalpha.xyz
    partners_host: http://partners.test.searchalpha.xyz
    partnersadmin_host: http://partnersadmin.test.searchalpha.xyz
    bdadmin_host: http://bdadmin.test.searchalpha.xyz
    spotAdmin_host: http://spotwebadmin.test.searchalpha.xyz
    featuresAdmin_host: http://futureswebadmin.test.searchalpha.xyz
    web_host: http://www.test.searchalpha.xyz
    partnersadmin_account: admin
    partnersadmin_password: admin
    partner_email: gerow@126.com
    bd_email: gerow@bitunix.io
    bd_name: gerow
    userName: gerow.wang@bitunix.io
    password: Aa123456
    spotAdminGoogleCode: OQNW3ZHMS7UIVO2F
    featuresAdminGoogleCode: ZXHYKFQ6PGTM72V7
    Accept-Language: en_US
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"