data:
  test:
    platform: bitunix
    host: api.bitunix.one
    xxljob_host: https://xxljob.bitunix.one
    partners_host: https://partners.bitunix.one
    partnersadmin_host: https://partnersadmin.bitunix.one
    bdadmin_host: https://bdadmin.bitunix.one
    spotwebadmin_host: https://spotwebadmin.bitunix.one
    userName: gerow.wang@bitunix.io
    password: Aa123456
    googleCode: 6XYRQBKYF2NCLSCF
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"