data:
  test:
    platform: tanmarket
    host: blue.wechatsi.com
client:
  headers:
    Authorization: |
      eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzkzNzg5ODEsInBheWxvYWQiOiJ7XCJjb3JwaWRcIjpcInd3ZDA3NGYzOTY4ZjU2ZGNiMFwiLFwiaWRcIjo1MTE1MDE0MTcxNjI5NDQsXCJ1c2VySWRcIjpcImQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0MjdlXCIsXCJpc0FkbWluXCI6MCxcImRlcGFydG1lbnRJZHNcIjpudWxsLFwibWFuYWdlRGVwdHNcIjpcIltdXCIsXCJkZXZpY2VcIjpcIndlYlwiLFwibmFtZVwiOlwi546L5YGl5by6XCIsXCJ2YWd1ZVwiOjAsXCJfbGVhZGVyXCI6dHJ1ZX0iLCJleHAiOjE2Nzk1NTE3ODF9.BIQf2ePrBmhshLsF3UiCyLR-3vsBX9t9hFqCTF_V2uDrci_f-KvAT5a9ZBldfgDVmQoxnTzHxeoTT4SpRKnu2jWnQZes0vNU45KSgJ9_nUpoRIdOdMsYbOGeklDnb9sTi-mhfMs5DNcm89tqhVyfZjrrMxm1iP6ysROaEiyBgyve8SCI6_41ksXnA5D0XfVDWHaYMiRFHcTtBRbzglsPLAhaWwKYKWzAZfEXNU2O_Fyj0EJnuNw3SLYOfOuB01dJhvfo5NFOvfLy3q7IgoufHvDYXPPqkV1zAdNltS_t3Ca_aP4N-lF7jPMsaNlmtaYxrTbEkLv4ZeZB__udFfrHIw
      
