data:
  test:
    platform: tanmarket
    host: blue.wechatsi.com
    userId: ${userId}
    password: ${password}
    userName: 王健强
    userName2: GerowWang
    appId: wwd074f3968f56dcb0_MUVXzH
    appKey: OtfNkhTNnGC45aRL37y1m50R17dba9wG

