data:
  test:
    platform: bitunix
    host: api.bitunix.one
    partners_host: https://partners.bitunix.one
    partnersadmin_host: https://partnersadmin.bitunix.one
    bdadmin_host: https://bdadmin.bitunix.one
    spotAdmin_host: https://spotwebadmin.bitunix.one
    web_host: https://www.bitunix.one
    partnersadmin_account: admin
    partnersadmin_password: admin
    partner_email: gerow@126.com
    bd_email: gerow@bitunix.io
    bd_name: gerow
    userName: gerow.wang@bitunix.io
    password: Aa123456
    spotAdminGoogleCode: 6XYRQBKYF2NCLSCF
    couponId: 248
client:
  protocol: https
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"