data:
  test:
    platform: bitunix
    host: api.testa.searchalpha.xyz
    partners_host: http://partners.testa.searchalpha.xyz
    partnersadmin_host: http://partnersadmin.testa.searchalpha.xyz
    bdadmin_host: http://bdadmin.testa.searchalpha.xyz
    spotAdmin_host: http://spotwebadmin.testa.searchalpha.xyz
    featuresAdmin_host: http://futureswebadmin.testa.searchalpha.xyz
    web_host: http://www.testa.searchalpha.xyz
    partnersadmin_account: admin
    partnersadmin_password: admin
    partner_email: gerow@126.com
    bd_email: gerow@bitunix.io
    bd_name: gerow
    userName: gerow.wang@bitunix.io
    password: Aa123456
    spotAdminGoogleCode: GGMNJZXCIFVBO6F5
    featuresAdminGoogleCode: ZXHYKFQ6PGTM72V7
    Accept-Language: zh_CN
    couponId: 3
    symbol: BTCUSDT
    amount: 0.05
    userId: 49650
client:
  protocol: http
  timeOut: 30
  headers:
    Content-Type: "application/json;charset=UTF-8"
    Accept-Language: zh_CN