data:
  test:
    platform: tanmarket
    host: beta.tanmarket.cn
    userId: ${userId}
    password: ${password}
    userName: 王健强
    appId: ww03d0b79073a82f04_sioeHG
    appKey: yKEfw0JoMWpd5VXym3Iyn9nIDyyA1bq6